#!/usr/bin/env python3
"""
Generate the Well Spring Intervention LLC SOP Manual body PDF.

Structure:
  - TOC (auto-generated via TocDocTemplate.multiBuild)
  - PART 1: Standard Operating Procedures (10 sections)
  - PART 2: Actionable Workflows & Protocols (19 protocols)
  - PART 3: Customized Forms & Logs (6 forms, several with tables)

Cover page is rendered separately via html2poster.js and merged in
via merge_sop.py. Therefore body page N becomes final page N+1, and
all TOC entries / footer page numbers are offset by +1.
"""

import os
import sys
import hashlib
import platform

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, CondPageBreak, HRFlowable, Flowable,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ────────────────────────────────────────────────────────────────────
# Font registration
# ────────────────────────────────────────────────────────────────────
_IS_MAC = platform.system() == 'Darwin'
FONT_DIR = os.path.expanduser('~/.openclaw/workspace/fonts') if _IS_MAC else '/usr/share/fonts'

pdfmetrics.registerFont(TTFont('NotoSerifSC',      f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
# Noto Sans SC is a variable font on this system (NotoSansSC[wght].ttf); skip registration.
# install_font_fallback() will fall back to NotoSerifSC for any non-Latin glyphs.
pdfmetrics.registerFont(TTFont('FreeSerif',           f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold',      f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic',    f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic',f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('NotoSerifSC',  normal='NotoSerifSC',  bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif',    normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans',   normal='DejaVuSans', bold='DejaVuSans')

# Install font fallback (auto-wraps missing-glyph chars)
sys.path.insert(0, '/home/z/my-project/skills/pdf/scripts')
from pdf import install_font_fallback
install_font_fallback()

# ────────────────────────────────────────────────────────────────────
# Cascade palette (auto-generated by palette.cascade)
# ────────────────────────────────────────────────────────────────────
PAGE_BG       = colors.HexColor('#f4f4f3')
SECTION_BG    = colors.HexColor('#eeedec')
CARD_BG       = colors.HexColor('#f0edec')
TABLE_STRIPE  = colors.HexColor('#f3f2f1')
HEADER_FILL   = colors.HexColor('#6b4d3f')
COVER_BLOCK   = colors.HexColor('#6a5145')
BORDER        = colors.HexColor('#beb0a9')
ICON          = colors.HexColor('#955b3e')
ACCENT        = colors.HexColor('#ab5125')
ACCENT_2      = colors.HexColor('#d15287')
TEXT_PRIMARY  = colors.HexColor('#1e1c1b')
TEXT_MUTED    = colors.HexColor('#87807d')
SEM_SUCCESS   = colors.HexColor('#43975f')
SEM_WARNING   = colors.HexColor('#917a4e')
SEM_ERROR     = colors.HexColor('#924c45')
SEM_INFO      = colors.HexColor('#4a6682')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ────────────────────────────────────────────────────────────────────
# Page geometry
# ────────────────────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
LEFT_M = 0.85 * inch
RIGHT_M = 0.85 * inch
TOP_M = 0.95 * inch
BOTTOM_M = 0.85 * inch
AVAIL_W = PAGE_W - LEFT_M - RIGHT_M  # ~440pt

# ────────────────────────────────────────────────────────────────────
# Self-reference — this manual cites itself alongside external regs
# ────────────────────────────────────────────────────────────────────
SELF_REF = (
    'Well Spring Intervention LLC SOP &amp; Operational Manual '
    '(Doc. WSI-SOP-001, Rev. 2.23, Aug 2026 — Legislation-Free Public Edition)'
)

# ────────────────────────────────────────────────────────────────────
# Paragraph styles
# ────────────────────────────────────────────────────────────────────
BODY_FONT = 'FreeSerif'
BODY_BOLD = 'FreeSerif-Bold'
BODY_ITAL = 'FreeSerif-Italic'

s_part = ParagraphStyle(
    name='PartHeading', fontName=BODY_BOLD, fontSize=22, leading=28,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=4, spaceAfter=4,
)
s_part_kicker = ParagraphStyle(
    name='PartKicker', fontName=BODY_BOLD, fontSize=10, leading=14,
    textColor=ACCENT, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=4,
)
s_part_intro = ParagraphStyle(
    name='PartIntro', fontName=BODY_ITAL, fontSize=11, leading=16,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=6, spaceAfter=14,
)

s_h1 = ParagraphStyle(
    name='H1', fontName=BODY_BOLD, fontSize=15, leading=20,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=14, spaceAfter=6,
)
s_h2 = ParagraphStyle(
    name='H2', fontName=BODY_BOLD, fontSize=11.5, leading=15,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=8, spaceAfter=3,
)

s_body = ParagraphStyle(
    name='Body', fontName=BODY_FONT, fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=6,
)
s_body_just = ParagraphStyle(
    name='BodyJust', parent=s_body, alignment=TA_JUSTIFY,
)

s_ref = ParagraphStyle(
    name='Ref', fontName=BODY_ITAL, fontSize=8.5, leading=12,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=6,
)

s_bullet = ParagraphStyle(
    name='Bullet', fontName=BODY_FONT, fontSize=10, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=18, bulletIndent=4,
    spaceBefore=1, spaceAfter=1,
)

s_callout = ParagraphStyle(
    name='Callout', fontName=BODY_FONT, fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=10, rightIndent=10,
    spaceBefore=4, spaceAfter=4,
)
s_callout_label = ParagraphStyle(
    name='CalloutLabel', fontName=BODY_BOLD, fontSize=8.5, leading=11,
    textColor=ACCENT, alignment=TA_LEFT,
    leftIndent=10, rightIndent=10,
    spaceBefore=4, spaceAfter=2,
)

s_form_title = ParagraphStyle(
    name='FormTitle', fontName=BODY_BOLD, fontSize=12, leading=16,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=12, spaceAfter=2,
)
s_form_meta = ParagraphStyle(
    name='FormMeta', fontName=BODY_FONT, fontSize=9.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=2,
)
s_form_instr = ParagraphStyle(
    name='FormInstr', fontName=BODY_ITAL, fontSize=9, leading=12,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=2, spaceAfter=4,
)
s_form_section = ParagraphStyle(
    name='FormSection', fontName=BODY_BOLD, fontSize=10, leading=13,
    textColor=ACCENT, alignment=TA_LEFT,
    spaceBefore=6, spaceAfter=2,
)

# Table cell styles
s_th = ParagraphStyle(
    name='TH', fontName=BODY_BOLD, fontSize=9.5, leading=12,
    textColor=colors.white, alignment=TA_CENTER,
)
s_th_left = ParagraphStyle(
    name='THLeft', parent=s_th, alignment=TA_LEFT,
)
s_td = ParagraphStyle(
    name='TD', fontName=BODY_FONT, fontSize=9, leading=12,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
s_td_c = ParagraphStyle(
    name='TDC', parent=s_td, alignment=TA_CENTER,
)
s_td_b = ParagraphStyle(
    name='TDB', parent=s_td, fontName=BODY_BOLD,
)
s_td_sm = ParagraphStyle(
    name='TDSM', fontName=BODY_FONT, fontSize=8, leading=10,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER,
)

# TOC styles
s_toc_title = ParagraphStyle(
    name='TOCTitle', fontName=BODY_BOLD, fontSize=24, leading=30,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceAfter=4,
)
s_toc_kicker = ParagraphStyle(
    name='TOCKicker', fontName=BODY_BOLD, fontSize=10, leading=14,
    textColor=ACCENT, alignment=TA_LEFT,
    spaceAfter=4,
)
s_toc_intro = ParagraphStyle(
    name='TOCIntro', fontName=BODY_ITAL, fontSize=10, leading=14,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceAfter=20,
)
s_toc_l0 = ParagraphStyle(
    name='TOC0', fontName=BODY_BOLD, fontSize=12, leading=18,
    textColor=HEADER_FILL, leftIndent=0,
    spaceBefore=10, spaceAfter=4,
)
s_toc_l1 = ParagraphStyle(
    name='TOC1', fontName=BODY_FONT, fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, leftIndent=20,
    spaceBefore=1, spaceAfter=1,
)

# ────────────────────────────────────────────────────────────────────
# TocDocTemplate (offset page numbers by +1 for merged cover)
# ────────────────────────────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # +2 offset: cover is page 1, About This Manual is page 2 after merging,
            # so body page 1 (TOC) becomes page 3 in the final PDF.
            self.notify('TOCEntry', (level, text, self.page + 2, key))


# ────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────
def _key(text):
    return 'h_' + hashlib.md5(text.encode('utf-8')).hexdigest()[:8]


def add_heading(text, style, level=0):
    """Heading flowable with TOC bookmark."""
    k = _key(text)
    p = Paragraph(f'<a name="{k}"/>{text}', style)
    p.bookmark_name = k
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = k
    return p


def part_divider(kicker, title, intro):
    """Major part divider: kicker + title + intro paragraph + accent rule."""
    return [
        CondPageBreak(PAGE_H * 0.35),
        Spacer(1, 18),
        Paragraph(kicker, s_part_kicker),
        add_heading(title, s_part, level=0),
        HRFlowable(width=80, color=ACCENT, thickness=2, spaceBefore=2, spaceAfter=10),
        Paragraph(intro, s_part_intro),
    ]


def section_heading(num, title):
    """Numbered SOP/protocol/form heading."""
    return add_heading(f'{num}. {title}', s_h1, level=1)


def ref_line(external=None, anchor=None):
    """Reference line. ALWAYS cites this manual itself (the SOP file).
    Optionally prepends external regulatory citations and/or appends a
    section anchor (e.g., '§1' or 'Part 2 · Protocol 3')."""
    parts = []
    if external:
        parts.append(external)
    parts.append(SELF_REF)
    if anchor:
        parts.append(anchor)
    return Paragraph(f'<i>Reference: {" &middot; ".join(parts)}</i>', s_ref)


def para(text, justify=False):
    return Paragraph(text, s_body_just if justify else s_body)


def bullets(items, indent=18):
    out = []
    for it in items:
        if isinstance(it, tuple):
            label, body = it
            out.append(Paragraph(f'<b>{label}</b> {body}', s_bullet))
        else:
            out.append(Paragraph(it, s_bullet))
    return out


def callout(label, lines):
    """Accent-bordered callout box."""
    inner = [Paragraph(label.upper(), s_callout_label)]
    for ln in lines:
        inner.append(Paragraph(ln, s_callout))
    tbl = Table([[inner]], colWidths=[AVAIL_W], hAlign='CENTER')
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    return tbl


def std_table(header_row, body_rows, col_widths, header_align='center',
              first_col_left=False, small=False):
    """Standard table with cascade-palette header, alternating stripes."""
    th_style = s_th_left if header_align == 'left' else s_th
    td_base = s_td_sm if small else s_td
    td_c = ParagraphStyle('tdc_' + str(small), parent=td_base, alignment=TA_CENTER)
    td_l = ParagraphStyle('tdl_' + str(small), parent=td_base, alignment=TA_LEFT)

    data = [[Paragraph(f'<b>{h}</b>', th_style) for h in header_row]]
    for row in body_rows:
        out_row = []
        for i, cell in enumerate(row):
            sty = td_l if (first_col_left and i == 0) else td_c
            out_row.append(Paragraph(str(cell), sty))
        data.append(out_row)

    tbl = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ('GRID',       (0, 0), (-1, -1), 0.4, BORDER),
        ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING',  (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING',   (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 1 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def form_table(data_rows, col_widths, has_header=False):
    """Blank form-style table (no alternating stripes; transparent)."""
    tbl = Table(data_rows, colWidths=col_widths, hAlign='CENTER',
                repeatRows=1 if has_header else 0)
    style_cmds = [
        ('GRID',       (0, 0), (-1, -1), 0.6, BORDER),
        ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING',  (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING',   (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 6),
    ]
    if has_header:
        style_cmds += [
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
            ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ]
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def signature_line(label, width_pct=0.46):
    """Inline signature line: label + underscored blank."""
    w = AVAIL_W * width_pct
    p = Paragraph(f'<b>{label}</b>: __________________________________', s_form_meta)
    return p


# ────────────────────────────────────────────────────────────────────
# AcroForm fillable field helpers (printable / copyable / sharable / editable / fillable)
# ────────────────────────────────────────────────────────────────────
_acro_field_counter = [0]

def _next_acro_name(prefix='f'):
    """Return a unique AcroForm field name (PDF requires unique names per field)."""
    _acro_field_counter[0] += 1
    return f'{prefix}_{_acro_field_counter[0]:04d}'


class AcroTextField(Flowable):
    """A Platypus Flowable that renders an interactive AcroForm text field.

    Drop into any Table cell (or use inline alongside Paragraphs) to make that
    cell fillable. In a PDF reader that supports AcroForm (Adobe Acrobat,
    Preview, Foxit, browsers), the user can click and type directly into the
    field. The field can be saved, printed, copied, and shared like any PDF
    content.
    """
    def __init__(self, name=None, width=120, height=14, tooltip='', value='',
                 font_size=9, border_style='underlined', border_width=0):
        Flowable.__init__(self)
        self.name = name or _next_acro_name('tf')
        self.width = width
        self.height = height
        self.tooltip = tooltip or self.name
        self.value = value
        self.font_size = font_size
        self.border_style = border_style
        self.border_width = border_width

    def wrap(self, availWidth, availHeight):
        # Respect requested size but never exceed available space
        w = min(self.width, availWidth) if availWidth else self.width
        h = min(self.height, availHeight) if availHeight else self.height
        self._w, self._h = w, h
        return (w, h)

    def draw(self):
        form = self.canv.acroForm
        form.textfield(
            name=self.name,
            tooltip=self.tooltip,
            x=0, y=0,
            width=self._w, height=self._h,
            borderStyle=self.border_style,
            forceBorder=False,
            borderWidth=self.border_width,
            fontName='Helvetica',
            fontSize=self.font_size,
            fillColor=None,
            textColor=colors.HexColor('#1e1c1b'),
            fieldFlags='',
            value=self.value,
        )


class AcroCheckbox(Flowable):
    """A Platypus Flowable that renders an interactive AcroForm checkbox."""
    def __init__(self, name=None, size=11, tooltip='', checked=False):
        Flowable.__init__(self)
        self.name = name or _next_acro_name('cb')
        self.size = size
        self.tooltip = tooltip or self.name
        self.checked = checked

    def wrap(self, availWidth, availHeight):
        s = min(self.size, availWidth) if availWidth else self.size
        self._s = s
        return (s, s)

    def draw(self):
        form = self.canv.acroForm
        form.checkbox(
            name=self.name,
            tooltip=self.tooltip,
            x=0, y=0,
            size=self._s,
            checked=self.checked,
            buttonStyle='check',
            borderStyle='inset',
            borderWidth=0.5,
            forceBorder=True,
            fillColor=colors.white,
            textColor=colors.HexColor('#1e1c1b'),
            borderColor=colors.HexColor('#87807d'),
        )


def fillable_meta_row(fields, col_widths=None, font_size=9.5, height=15):
    """Build a Table row where each (label, field_width, tooltip) tuple becomes
    a label + AcroTextField pair. Returns a Table flowable that can be appended
    to the story.

    `fields` is a list of (label, field_width_pts, tooltip) tuples. If
    field_width is 0 or None, the label is rendered as label-only (no text
    field) — useful for header labels that precede a checkbox row.
    `col_widths` is optional; if omitted, columns are sized to fit labels+fields
    and the total is auto-scaled to AVAIL_W so the row never overflows.
    """
    cells = []
    widths = []
    for label, fw, tip in fields:
        label_p = Paragraph(f'<b>{label}</b>', s_form_meta)
        if fw and fw > 0:
            tf = AcroTextField(width=fw, height=height, tooltip=tip, font_size=font_size)
            cells.extend([label_p, tf])
            lw = max(40, len(label) * 5.5 + 8)
            widths.extend([lw, fw])
        else:
            # Label-only entry (no text field)
            cells.append(label_p)
            lw = max(40, len(label) * 5.5 + 8)
            widths.append(lw)
    if col_widths:
        widths = col_widths
    else:
        # Auto-scale to fit within AVAIL_W (with a small margin for padding)
        total = sum(widths)
        target = AVAIL_W - 8  # account for default 2+6 padding per cell pair
        if total > target:
            scale = target / total
            widths = [w * scale for w in widths]
    tbl = Table([cells], colWidths=widths, hAlign='CENTER')
    tbl.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 2),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    return tbl


def fillable_check_row(items, font_size=9.5, box_size=11):
    """Build a Table row where each item becomes a checkbox + label pair.

    `items` is a list of (label, tooltip) tuples; tooltip may be ''.
    """
    cells = []
    for label, tip in items:
        cells.append(AcroCheckbox(size=box_size, tooltip=tip or label))
        cells.append(Paragraph(label, s_form_meta))
    tbl = Table([cells], hAlign='LEFT')
    tbl.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 2),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    return tbl


def fillable_signature_row(items, height=15, font_size=9.5):
    """Build a Table row of (label, field_width, tooltip) signature fields
    laid out horizontally. Designed for signature/date/description lines.
    """
    return fillable_meta_row(items, font_size=font_size, height=height)


def form_usage_banner(form_number=None):
    """Styled banner declaring the form's capabilities: printable, copyable,
    sharable, editable, fillable. Appended above each form to communicate the
    form's interactive properties to the user.
    """
    s_banner_label = ParagraphStyle(
        name='FormBannerLabel', fontName=BODY_BOLD, fontSize=8, leading=11,
        textColor=ACCENT, alignment=TA_LEFT,
    )
    s_banner_body = ParagraphStyle(
        name='FormBannerBody', fontName=BODY_FONT, fontSize=8.5, leading=11.5,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    )
    inner = [
        Paragraph('FORM PROPERTIES', s_banner_label),
        Paragraph(
            'This form is <b>printable</b>, <b>copyable</b>, <b>sharable</b>, '
            '<b>editable</b>, and <b>fillable</b>. '
            'Click any field to type. Save the PDF to retain entries. '
            'Print to obtain a wet-ink signature. Share the saved or printed '
            'copy via secure channels (encrypted email, EHR upload, or sealed '
            'envelope). Edit existing entries by clicking the field again. '
            'Standalone fillable copies of all forms are in the '
            '<i>/download/forms/</i> directory.',
            s_banner_body
        ),
    ]
    tbl = Table([[inner]], colWidths=[AVAIL_W], hAlign='CENTER')
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    return tbl


# ────────────────────────────────────────────────────────────────────
# Header / footer (drawn via onPage callback)
# ────────────────────────────────────────────────────────────────────
DOC_TITLE_SHORT = 'Standard Operating Procedure & Operational Manual — Rev. 2.22 (Public Edition)'
DOC_ORG = 'Well Spring Intervention LLC'

def draw_header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont('FreeSerif-Italic', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, PAGE_H - TOP_M * 0.55, DOC_TITLE_SHORT)
    canvas.drawRightString(PAGE_W - RIGHT_M, PAGE_H - TOP_M * 0.55, DOC_ORG)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_M, PAGE_H - TOP_M * 0.55 - 4,
                PAGE_W - RIGHT_M, PAGE_H - TOP_M * 0.55 - 4)

    # Footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_M, BOTTOM_M * 0.55 + 14,
                PAGE_W - RIGHT_M, BOTTOM_M * 0.55 + 14)
    canvas.setFont('FreeSerif-Italic', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, BOTTOM_M * 0.55, 'Confidential — Internal Use Only')
    # Page number with +1 offset for merged cover
    page_num = canvas.getPageNumber() + 1
    canvas.drawRightString(PAGE_W - RIGHT_M, BOTTOM_M * 0.55, f'Page {page_num}')
    canvas.restoreState()


# ────────────────────────────────────────────────────────────────────
# Content builders — Version 2.0 (RMDM-Compliant, July 2026)
# 11 SOP sections + 21 protocols + 9 forms + version history
# Content lives in separate modules for maintainability.
# Imports are deferred to inside build() to avoid circular imports.
# ────────────────────────────────────────────────────────────────────


# ────────────────────────────────────────────────────────────────────
# Main — build the body PDF
# ────────────────────────────────────────────────────────────────────
OUTPUT_BODY = '/home/z/my-project/scripts/sop_body.pdf'

def build():
    # Deferred imports — content modules need access to the helpers/styles
    # defined above, so we import them here (after all symbols exist).
    from sop_content_v3 import build_part1
    from sop_content_v3_part2 import build_part2
    from sop_content_v3_part3 import build_part3

    doc = TocDocTemplate(
        OUTPUT_BODY,
        pagesize=A4,
        leftMargin=LEFT_M, rightMargin=RIGHT_M,
        topMargin=TOP_M, bottomMargin=BOTTOM_M,
        title='Well Spring Intervention LLC — SOP & Operational Manual',
        author='Well Spring Intervention LLC',
        creator='Z.ai',
        subject='Level 3 Supervised Residential Group Home — Standard Operating Procedures (Rev. 2.23 Legislation-Free Public Edition)',
        keywords='SOP, residential group home, Level 3, operations manual, trauma-informed care, RMDM, HIPAA',
    )

    story = []

    # ── About This Manual (inside cover page) ─────────────────────────
    # The cover is now a full-bleed brand illustration with minimal overlay
    # text only. All descriptive content (summary, meta, regulatory framework)
    # is moved here so the cover can serve as a reusable brand asset.
    story.append(Paragraph('ABOUT THIS MANUAL', s_toc_kicker))
    story.append(Paragraph('Document Overview', s_toc_title))
    story.append(HRFlowable(width=80, color=ACCENT, thickness=2, spaceBefore=2, spaceAfter=14))

    story.append(Paragraph(
        'This manual (Rev. 2.23, August 2026) is the official Standard Operating '
        'Procedures and Operational Reference for <b>Well Spring Intervention LLC</b>, '
        'a Level 3 Supervised Residential Group Home serving children and '
        'adolescents with mental health and behavioral challenges. It establishes '
        'the policies, actionable workflows, and reference forms governing the '
        'daily operation of the program. All staff are required to read, '
        'acknowledge, and follow these protocols exactly as written.',
        s_body
    ))
    story.append(Spacer(1, 6))

    # Meta block (moved from cover)
    story.append(Paragraph('<b>Population Served.</b> Children &amp; Adolescents — Mental Health / Behavioral Challenges.', s_body))
    story.append(Paragraph('<b>Service Type.</b> Level 3 Supervised Residential Group Home.', s_body))
    story.append(Paragraph('<b>Effective Date.</b> July 2026.', s_body))
    story.append(Paragraph('<b>Document Owner.</b> Executive Director &amp; Qualified Professional (QP).', s_body))
    story.append(Paragraph('<b>Document ID.</b> Doc. WSI-SOP-001, Rev. 2.23 (Legislation-Free Public Edition). <i>The companion compliance master (Doc. WSI-SOP-001-LEG, Rev. 2.21) retains all statutory and regulatory citations for QA and audit reference.</i>', s_body))
    story.append(Spacer(1, 10))

    # Regulatory framework (operational language — legislation retained in compliance master)
    story.append(Paragraph('<b>Operating Framework.</b>', s_h2))
    story.append(Paragraph(
        'This manual is governed by, and operates in conformance with, the following '
        'authorities: <b>NC DHSR</b> facility licensure as a Level III Residential '
        'Treatment Facility (Staff-Secure); <b>NC Medicaid</b> managed care requirements '
        'through our regional LME/MCO/Tailored Plan partner (Alliance Health); <b>NC '
        'DHSR</b> Mental Health Licensure and Certification Section standards; '
        '<b>LME/MCO Tailored Plan</b> requirements; the <b>NCDHHS Records Management '
        'and Documentation Manual</b> (RMDM, Effective July 8, 2025); <b>HIPAA</b> '
        'Privacy, Security, and Breach Notification Rules; <b>42 CFR Part 2</b> '
        '(confidentiality of SUD records); <b>HITECH Act</b>; state law on electronic '
        'transactions (NC UETA); and the federal <b>E-SIGN Act</b> governing electronic '
        'signatures. The full statutory and regulatory citation list is retained in the '
        'compliance master copy (Doc. WSI-SOP-001-LEG, Rev. 2.21) for QA and audit '
        'reference.',
        s_body
    ))
    story.append(Spacer(1, 10))

    # Brand visual note
    story.append(Paragraph('<b>Cover Artwork.</b>', s_h2))
    story.append(Paragraph(
        'The cover features the official circular brand seal of Well Spring '
        'Intervention LLC as its centerpiece. The seal is composed of a '
        'pentagonal house outline (with a floor, two vertical walls, two roof '
        'slopes meeting at a raised peak, and a horizontal ceiling line '
        'connecting the two top corner vertices) drawn in deep walnut-brown '
        'on a warm cream parchment background. Inside the house outline sits '
        'the company\'s multi-color logo imagery: a red heart-shaped tree '
        'canopy with green leaves above a brown tree trunk, family figures '
        '(two adults and one child) standing before the tree, and a blue '
        'wellspring fountain at the base. The full company name '
        '"Well Spring Intervention LLC" curves along the top arc between '
        'two bold concentric circular hairlines; the descriptor '
        '"Residential" curves along the bottom arc inside the inner '
        'hairline; and small terracotta accent dots and a closure ornament '
        'frame the composition. The house roof peak is set at the same '
        'radial distance from the seal center as the wall corners, so all '
        'three top vertices touch the same imaginary circle. The cover '
        'layout is a clean three-band composition: a compact top band '
        'carrying the "SOP / OPERATIONAL MANUAL" badge and the values '
        'tagline (Empowerment · Growth · Freedom · Health · Wholeness · '
        'Healing); a large middle band in which the cream seal square pops '
        'against the dark brown background as the clear focal point; and a '
        'bottom band carrying the document title "SOP & Operational '
        'Manual", the subtitle "Standard Operating Procedures, Protocols '
        '& Forms", and the website URL. The seal symbolizes the program\'s '
        'commitment to empowerment, growth, freedom, health, wholeness, and '
        'healing, and is approved for reuse across company websites, '
        'publications, and collateral materials. High-resolution copies of '
        'the seal (in both a square variant for avatar/profile-pic use and '
        'a variant with the website URL below the circle) are available '
        'alongside this manual for that purpose.',
        s_body
    ))
    story.append(PageBreak())

    # ── TOC page ──────────────────────────────────────────────────────
    story.append(Paragraph('CONTENTS', s_toc_kicker))
    story.append(Paragraph('Table of Contents', s_toc_title))
    story.append(HRFlowable(width=80, color=ACCENT, thickness=2, spaceBefore=2, spaceAfter=12))
    story.append(Paragraph(
        'This manual (Rev. 2.23, August 2026) is organized into three parts and is fully '
        'compliant with the NCDHHS Records Management and Documentation Manual (RMDM, '
        'Effective July 8, 2025). Part 1 establishes foundational policies and compliance '
        'obligations across eleven sections, including dedicated chapters on '
        'privacy/confidentiality and an expanded Medicaid documentation section. '
        'Part 2 details twenty-two step-by-step workflows that govern daily operations, '
        'including protocols for service orders/authorizations and record '
        'management/disclosure accounting. Part 3 provides nine customized forms '
        'and logs, including the Full Service Note Template, Comprehensive Clinical '
        'Record Content Checklist, Accounting of Disclosures Log, the Licensed '
        'Professional Consultation Log (new in v2.23), and the Psychotropic Medication '
        'Drug Regimen Review Log (new in v2.23). A complete revision history appears '
        'in the Version History table at the end of Part 3.',
        s_toc_intro
    ))

    toc = TableOfContents()
    toc.levelStyles = [s_toc_l0, s_toc_l1]
    story.append(toc)
    story.append(PageBreak())

    # Three parts
    story.extend(build_part1())
    story.extend(build_part2())
    story.extend(build_part3())

    doc.multiBuild(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
    print(f'Body PDF written: {OUTPUT_BODY}')


if __name__ == '__main__':
    build()
