#!/usr/bin/env python3
"""
Generate the Well Spring Intervention LLC SOP Manual body PDF.

Structure:
  - TOC (auto-generated via TocDocTemplate.multiBuild)
  - PART 1: Standard Operating Procedures (10 sections)
  - PART 2: Actionable Workflows & Protocols (19 protocols)
  - PART 3: Customized Forms & Logs (6 forms, several with tables)

Cover page is rendered separately via html2poster.js and merged in
via merge_sop.py. Therefore body page N becomes final page N+1, and
all TOC entries / footer page numbers are offset by +1.
"""

import os
import sys
import hashlib
import platform

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, CondPageBreak, HRFlowable, Flowable,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ────────────────────────────────────────────────────────────────────
# Font registration
# ────────────────────────────────────────────────────────────────────
_IS_MAC = platform.system() == 'Darwin'
FONT_DIR = os.path.expanduser('~/.openclaw/workspace/fonts') if _IS_MAC else '/usr/share/fonts'

pdfmetrics.registerFont(TTFont('NotoSerifSC',      f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
# Noto Sans SC is a variable font on this system (NotoSansSC[wght].ttf); skip registration.
# install_font_fallback() will fall back to NotoSerifSC for any non-Latin glyphs.
pdfmetrics.registerFont(TTFont('FreeSerif',           f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold',      f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic',    f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic',f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('NotoSerifSC',  normal='NotoSerifSC',  bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif',    normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans',   normal='DejaVuSans', bold='DejaVuSans')

# Install font fallback (auto-wraps missing-glyph chars)
sys.path.insert(0, '/home/z/my-project/skills/pdf/scripts')
from pdf import install_font_fallback
install_font_fallback()

# ────────────────────────────────────────────────────────────────────
# Cascade palette (auto-generated by palette.cascade)
# ────────────────────────────────────────────────────────────────────
PAGE_BG       = colors.HexColor('#f4f4f3')
SECTION_BG    = colors.HexColor('#eeedec')
CARD_BG       = colors.HexColor('#f0edec')
TABLE_STRIPE  = colors.HexColor('#f3f2f1')
HEADER_FILL   = colors.HexColor('#6b4d3f')
COVER_BLOCK   = colors.HexColor('#6a5145')
BORDER        = colors.HexColor('#beb0a9')
ICON          = colors.HexColor('#955b3e')
ACCENT        = colors.HexColor('#ab5125')
ACCENT_2      = colors.HexColor('#d15287')
TEXT_PRIMARY  = colors.HexColor('#1e1c1b')
TEXT_MUTED    = colors.HexColor('#87807d')
SEM_SUCCESS   = colors.HexColor('#43975f')
SEM_WARNING   = colors.HexColor('#917a4e')
SEM_ERROR     = colors.HexColor('#924c45')
SEM_INFO      = colors.HexColor('#4a6682')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ────────────────────────────────────────────────────────────────────
# Page geometry
# ────────────────────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
LEFT_M = 0.85 * inch
RIGHT_M = 0.85 * inch
TOP_M = 0.95 * inch
BOTTOM_M = 0.85 * inch
AVAIL_W = PAGE_W - LEFT_M - RIGHT_M  # ~440pt

# ────────────────────────────────────────────────────────────────────
# Self-reference — this manual cites itself alongside external regs
# ────────────────────────────────────────────────────────────────────
SELF_REF = (
    'Well Spring Intervention LLC SOP &amp; Operational Manual '
    '(Doc. WSI-SOP-001, Rev. 2.5, Jul 2026 — RMDM-Compliant)'
)

# ────────────────────────────────────────────────────────────────────
# Paragraph styles
# ────────────────────────────────────────────────────────────────────
BODY_FONT = 'FreeSerif'
BODY_BOLD = 'FreeSerif-Bold'
BODY_ITAL = 'FreeSerif-Italic'

s_part = ParagraphStyle(
    name='PartHeading', fontName=BODY_BOLD, fontSize=22, leading=28,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=4, spaceAfter=4,
)
s_part_kicker = ParagraphStyle(
    name='PartKicker', fontName=BODY_BOLD, fontSize=10, leading=14,
    textColor=ACCENT, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=4,
)
s_part_intro = ParagraphStyle(
    name='PartIntro', fontName=BODY_ITAL, fontSize=11, leading=16,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=6, spaceAfter=14,
)

s_h1 = ParagraphStyle(
    name='H1', fontName=BODY_BOLD, fontSize=15, leading=20,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=14, spaceAfter=6,
)
s_h2 = ParagraphStyle(
    name='H2', fontName=BODY_BOLD, fontSize=11.5, leading=15,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=8, spaceAfter=3,
)

s_body = ParagraphStyle(
    name='Body', fontName=BODY_FONT, fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=6,
)
s_body_just = ParagraphStyle(
    name='BodyJust', parent=s_body, alignment=TA_JUSTIFY,
)

s_ref = ParagraphStyle(
    name='Ref', fontName=BODY_ITAL, fontSize=8.5, leading=12,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=6,
)

s_bullet = ParagraphStyle(
    name='Bullet', fontName=BODY_FONT, fontSize=10, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=18, bulletIndent=4,
    spaceBefore=1, spaceAfter=1,
)

s_callout = ParagraphStyle(
    name='Callout', fontName=BODY_FONT, fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=10, rightIndent=10,
    spaceBefore=4, spaceAfter=4,
)
s_callout_label = ParagraphStyle(
    name='CalloutLabel', fontName=BODY_BOLD, fontSize=8.5, leading=11,
    textColor=ACCENT, alignment=TA_LEFT,
    leftIndent=10, rightIndent=10,
    spaceBefore=4, spaceAfter=2,
)

s_form_title = ParagraphStyle(
    name='FormTitle', fontName=BODY_BOLD, fontSize=12, leading=16,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=12, spaceAfter=2,
)
s_form_meta = ParagraphStyle(
    name='FormMeta', fontName=BODY_FONT, fontSize=9.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=0, spaceAfter=2,
)
s_form_instr = ParagraphStyle(
    name='FormInstr', fontName=BODY_ITAL, fontSize=9, leading=12,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=2, spaceAfter=4,
)
s_form_section = ParagraphStyle(
    name='FormSection', fontName=BODY_BOLD, fontSize=10, leading=13,
    textColor=ACCENT, alignment=TA_LEFT,
    spaceBefore=6, spaceAfter=2,
)

# Table cell styles
s_th = ParagraphStyle(
    name='TH', fontName=BODY_BOLD, fontSize=9.5, leading=12,
    textColor=colors.white, alignment=TA_CENTER,
)
s_th_left = ParagraphStyle(
    name='THLeft', parent=s_th, alignment=TA_LEFT,
)
s_td = ParagraphStyle(
    name='TD', fontName=BODY_FONT, fontSize=9, leading=12,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
s_td_c = ParagraphStyle(
    name='TDC', parent=s_td, alignment=TA_CENTER,
)
s_td_b = ParagraphStyle(
    name='TDB', parent=s_td, fontName=BODY_BOLD,
)
s_td_sm = ParagraphStyle(
    name='TDSM', fontName=BODY_FONT, fontSize=8, leading=10,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER,
)

# TOC styles
s_toc_title = ParagraphStyle(
    name='TOCTitle', fontName=BODY_BOLD, fontSize=24, leading=30,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceAfter=4,
)
s_toc_kicker = ParagraphStyle(
    name='TOCKicker', fontName=BODY_BOLD, fontSize=10, leading=14,
    textColor=ACCENT, alignment=TA_LEFT,
    spaceAfter=4,
)
s_toc_intro = ParagraphStyle(
    name='TOCIntro', fontName=BODY_ITAL, fontSize=10, leading=14,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceAfter=20,
)
s_toc_l0 = ParagraphStyle(
    name='TOC0', fontName=BODY_BOLD, fontSize=12, leading=18,
    textColor=HEADER_FILL, leftIndent=0,
    spaceBefore=10, spaceAfter=4,
)
s_toc_l1 = ParagraphStyle(
    name='TOC1', fontName=BODY_FONT, fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, leftIndent=20,
    spaceBefore=1, spaceAfter=1,
)

# ────────────────────────────────────────────────────────────────────
# TocDocTemplate (offset page numbers by +1 for merged cover)
# ────────────────────────────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # +1 offset: cover page is page 1 after merging, body page 1 becomes page 2
            self.notify('TOCEntry', (level, text, self.page + 1, key))


# ────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────
def _key(text):
    return 'h_' + hashlib.md5(text.encode('utf-8')).hexdigest()[:8]


def add_heading(text, style, level=0):
    """Heading flowable with TOC bookmark."""
    k = _key(text)
    p = Paragraph(f'<a name="{k}"/>{text}', style)
    p.bookmark_name = k
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = k
    return p


def part_divider(kicker, title, intro):
    """Major part divider: kicker + title + intro paragraph + accent rule."""
    return [
        CondPageBreak(PAGE_H * 0.35),
        Spacer(1, 18),
        Paragraph(kicker, s_part_kicker),
        add_heading(title, s_part, level=0),
        HRFlowable(width=80, color=ACCENT, thickness=2, spaceBefore=2, spaceAfter=10),
        Paragraph(intro, s_part_intro),
    ]


def section_heading(num, title):
    """Numbered SOP/protocol/form heading."""
    return add_heading(f'{num}. {title}', s_h1, level=1)


def ref_line(external=None, anchor=None):
    """Reference line. ALWAYS cites this manual itself (the SOP file).
    Optionally prepends external regulatory citations and/or appends a
    section anchor (e.g., '§1' or 'Part 2 · Protocol 3')."""
    parts = []
    if external:
        parts.append(external)
    parts.append(SELF_REF)
    if anchor:
        parts.append(anchor)
    return Paragraph(f'<i>Reference: {" &middot; ".join(parts)}</i>', s_ref)


def para(text, justify=False):
    return Paragraph(text, s_body_just if justify else s_body)


def bullets(items, indent=18):
    out = []
    for it in items:
        if isinstance(it, tuple):
            label, body = it
            out.append(Paragraph(f'<b>{label}</b> {body}', s_bullet))
        else:
            out.append(Paragraph(it, s_bullet))
    return out


def callout(label, lines):
    """Accent-bordered callout box."""
    inner = [Paragraph(label.upper(), s_callout_label)]
    for ln in lines:
        inner.append(Paragraph(ln, s_callout))
    tbl = Table([[inner]], colWidths=[AVAIL_W], hAlign='CENTER')
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    return tbl


def std_table(header_row, body_rows, col_widths, header_align='center',
              first_col_left=False, small=False):
    """Standard table with cascade-palette header, alternating stripes."""
    th_style = s_th_left if header_align == 'left' else s_th
    td_base = s_td_sm if small else s_td
    td_c = ParagraphStyle('tdc_' + str(small), parent=td_base, alignment=TA_CENTER)
    td_l = ParagraphStyle('tdl_' + str(small), parent=td_base, alignment=TA_LEFT)

    data = [[Paragraph(f'<b>{h}</b>', th_style) for h in header_row]]
    for row in body_rows:
        out_row = []
        for i, cell in enumerate(row):
            sty = td_l if (first_col_left and i == 0) else td_c
            out_row.append(Paragraph(str(cell), sty))
        data.append(out_row)

    tbl = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ('GRID',       (0, 0), (-1, -1), 0.4, BORDER),
        ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING',  (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING',   (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 1 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def form_table(data_rows, col_widths, has_header=False):
    """Blank form-style table (no alternating stripes; transparent)."""
    tbl = Table(data_rows, colWidths=col_widths, hAlign='CENTER',
                repeatRows=1 if has_header else 0)
    style_cmds = [
        ('GRID',       (0, 0), (-1, -1), 0.6, BORDER),
        ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING',  (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING',   (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 6),
    ]
    if has_header:
        style_cmds += [
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
            ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ]
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def signature_line(label, width_pct=0.46):
    """Inline signature line: label + underscored blank."""
    w = AVAIL_W * width_pct
    p = Paragraph(f'<b>{label}</b>: __________________________________', s_form_meta)
    return p


# ────────────────────────────────────────────────────────────────────
# Header / footer (drawn via onPage callback)
# ────────────────────────────────────────────────────────────────────
DOC_TITLE_SHORT = 'Standard Operating Procedure & Operational Manual — Rev. 2.5 (RMDM-Compliant)'
DOC_ORG = 'Well Spring Intervention LLC'

def draw_header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont('FreeSerif-Italic', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, PAGE_H - TOP_M * 0.55, DOC_TITLE_SHORT)
    canvas.drawRightString(PAGE_W - RIGHT_M, PAGE_H - TOP_M * 0.55, DOC_ORG)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_M, PAGE_H - TOP_M * 0.55 - 4,
                PAGE_W - RIGHT_M, PAGE_H - TOP_M * 0.55 - 4)

    # Footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_M, BOTTOM_M * 0.55 + 14,
                PAGE_W - RIGHT_M, BOTTOM_M * 0.55 + 14)
    canvas.setFont('FreeSerif-Italic', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, BOTTOM_M * 0.55, 'Confidential — Internal Use Only')
    # Page number with +1 offset for merged cover
    page_num = canvas.getPageNumber() + 1
    canvas.drawRightString(PAGE_W - RIGHT_M, BOTTOM_M * 0.55, f'Page {page_num}')
    canvas.restoreState()


# ────────────────────────────────────────────────────────────────────
# Content builders — Version 2.0 (RMDM-Compliant, July 2026)
# 11 SOP sections + 21 protocols + 9 forms + version history
# Content lives in separate modules for maintainability.
# Imports are deferred to inside build() to avoid circular imports.
# ────────────────────────────────────────────────────────────────────


# ────────────────────────────────────────────────────────────────────
# Main — build the body PDF
# ────────────────────────────────────────────────────────────────────
OUTPUT_BODY = '/home/z/my-project/scripts/sop_body.pdf'

def build():
    # Deferred imports — content modules need access to the helpers/styles
    # defined above, so we import them here (after all symbols exist).
    from sop_content_v2 import build_part1
    from sop_content_v2_part2 import build_part2
    from sop_content_v2_part3 import build_part3

    doc = TocDocTemplate(
        OUTPUT_BODY,
        pagesize=A4,
        leftMargin=LEFT_M, rightMargin=RIGHT_M,
        topMargin=TOP_M, bottomMargin=BOTTOM_M,
        title='Well Spring Intervention LLC — SOP & Operational Manual',
        author='Well Spring Intervention LLC',
        creator='Z.ai',
        subject='Level 3 Supervised Residential Group Home — Standard Operating Procedures (Rev. 2.5 RMDM-Compliant)',
        keywords='SOP, residential group home, Level 3, NCAC 27G, Rule 108, Medicaid CCP 8C, IRIS, RMDM, HIPAA, 42 CFR Part 2, NCGS Ch. 66 Art. 40, E-SIGN, Electronic Signatures',
    )

    story = []

    # TOC page
    story.append(Paragraph('CONTENTS', s_toc_kicker))
    story.append(Paragraph('Table of Contents', s_toc_title))
    story.append(HRFlowable(width=80, color=ACCENT, thickness=2, spaceBefore=2, spaceAfter=12))
    story.append(Paragraph(
        'This manual (Rev. 2.5, July 2026) is organized into three parts and is fully '
        'compliant with the NCDHHS Records Management and Documentation Manual (RMDM, '
        'Effective July 8, 2025). Part 1 establishes foundational policies and compliance '
        'obligations across eleven sections, including new chapters on privacy/confidentiality '
        'and an expanded Medicaid documentation section. Rev. 2.1 added §10.7 Electronic '
        'Signatures (referencing NCGS Chapter 66, Article 40 — NC UETA) with explicit '
        'safeguards and system unavailability procedures. Rev. 2.2 clarified the '
        'organizational reporting structure in §1.4, establishing the QP as reporting to '
        'the Clinical Director, supervising staff per the Clinical Director\'s direction, '
        'and providing recurring compliance reports via new §1.4(a). Rev. 2.3 refined the '
        'QP responsibilities to explicitly include scheduling of clinical services, '
        'assessments, and PCPs in §1.4. Rev. 2.4 added §1.4(b) QP Credentialing '
        'Requirements per 10A NCAC 27G .0104. Rev. 2.5 corrects the §1.4(b) QP '
        'credentialing framework to recognize BOTH acceptable pathways: Pathway 1 '
        '(master\'s degree + recognized NC credential + 1 year post-master\'s supervised '
        'MH/DD/SA experience) and Pathway 2 (bachelor\'s degree + 2 years full-time '
        'pre- or post-bachelor\'s supervised MH/DD/SA experience); §2.2 QP bullet updated '
        'to match. Part 2 details twenty-one step-by-step workflows that govern daily '
        'operations, including protocols for service orders/authorizations and record '
        'management/disclosure accounting. Part 3 provides nine customized forms and '
        'logs, including the Full Service Note Template, Comprehensive Clinical Record '
        'Content Checklist, and Accounting of Disclosures Log.',
        s_toc_intro
    ))

    toc = TableOfContents()
    toc.levelStyles = [s_toc_l0, s_toc_l1]
    story.append(toc)
    story.append(PageBreak())

    # Three parts
    story.extend(build_part1())
    story.extend(build_part2())
    story.extend(build_part3())

    doc.multiBuild(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
    print(f'Body PDF written: {OUTPUT_BODY}')


if __name__ == '__main__':
    build()
